services:
  app:
    container_name: qna-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
      echo 'Ожидание базы...';
      until pg_isready -h $$DB_HOST -U $$DB_USER -d $$DB_NAME; do
        sleep 2;
      done;
      echo 'Применяем миграции...';
      alembic upgrade head;
      echo 'Запуск приложения...';
      exec uvicorn main:app --host 0.0.0.0 --port 8000
      "
    networks:
      - qna-network

  db:
    container_name: qna-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - qna-network

volumes:
  postgres_data:

networks:
  qna-network:
    driver: bridge